# netlify.toml

[build]
  # Tell Netlify where your static files are (the /client folder)
  publish = "client"
  # Set the build command (not strictly needed here, but good practice)
  command = "echo 'No build step required'"

[functions]
  # Tell Netlify where your serverless functions are
  directory = "netlify/functions"
  # This setting is necessary for ES Modules in Netlify Functions
  node_bundler = "esbuild"

# Redirects to map API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Optional: Redirect root (/) to the login page (since we removed app.get('/') from the serverless function)
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302 # Use 302 to allow browser caching